FROM postgres:17.11-alpine3.24

COPY migrations /migrations

ENTRYPOINT ["/bin/sh", "-ec"]
CMD ["for migration in /migrations/*.sql; do echo Applying $migration; psql \"$DATABASE_URL\" -v ON_ERROR_STOP=1 -f \"$migration\"; done"]
